
DROP TABLE IF EXISTS OS_PROPERTYENTRY;
DROP TABLE IF EXISTS OS_CURRENTSTEP_PREV;
DROP TABLE IF EXISTS OS_HISTORYSTEP_PREV;
DROP TABLE IF EXISTS OS_CURRENTSTEP;
DROP TABLE IF EXISTS OS_HISTORYSTEP;
DROP TABLE IF EXISTS OS_WFENTRY;

DROP SEQUENCE SEQ_OS_WFENTRY;
DROP SEQUENCE SEQ_OS_CURRENTSTEPS;

CREATE SEQUENCE SEQ_OS_WFENTRY INCREMENT 2 START 10;
CREATE SEQUENCE SEQ_OS_CURRENTSTEPS INCREMENT 2 START 10;

CREATE TABLE OS_WFENTRY
(
    ID int,
    NAME varchar(128),
    STATE smallint,
    primary key (ID)
);

CREATE TABLE OS_CURRENTSTEP
(
    ID int,
    ENTRY_ID int,
    STEP_ID smallint,
    ACTION_ID smallint,
    OWNER varchar(20),
    START_DATE TIMESTAMP ,
    FINISH_DATE TIMESTAMP ,
    DUE_DATE TIMESTAMP ,
    STATUS varchar(20),
    CALLER varchar(20),
    primary key (ID),
    foreign key (ENTRY_ID) references OS_WFENTRY(ID)

);

CREATE TABLE OS_HISTORYSTEP
(
    ID int,
    ENTRY_ID int,
    STEP_ID smallint,
    ACTION_ID smallint,
    OWNER varchar(20),
    START_DATE TIMESTAMP ,
    FINISH_DATE TIMESTAMP ,
    DUE_DATE TIMESTAMP ,
    STATUS varchar(20),
    CALLER varchar(20),
    primary key (ID),
    foreign key (ENTRY_ID) references OS_WFENTRY(ID)
);

CREATE TABLE OS_CURRENTSTEP_PREV
(
    ID int,
    PREVIOUS_ID int,
    primary key (ID, PREVIOUS_ID),
    foreign key (ID) references OS_CURRENTSTEP(ID),
    foreign key (PREVIOUS_ID) references OS_HISTORYSTEP(ID)
);

CREATE TABLE OS_HISTORYSTEP_PREV
(
    ID int,
    PREVIOUS_ID int,
    primary key (ID, PREVIOUS_ID),
    foreign key (ID) references OS_HISTORYSTEP(ID),
    foreign key (PREVIOUS_ID) references OS_HISTORYSTEP(ID)
);

CREATE TABLE SEQUENCE_VALUE_ITEM
(
   SEQ_NAME VARCHAR(60) NOT NULL,
   SEQ_ID int,
   CONSTRAINT PK_SEQUENCE_VALUE_ITEM PRIMARY KEY (SEQ_NAME)
);

CREATE TABLE OSGROUP
(
  id NUMERIC NOT NULL,
  name VARCHAR(255),
  CONSTRAINT PK_OSGROUP PRIMARY KEY (id)
);

CREATE TABLE OSMEMBERSHIP
(
  id NUMERIC NOT NULL,
  userId VARCHAR(255),
  groupId VARCHAR(255),
  CONSTRAINT PK_OSMEMBERSHIP PRIMARY KEY (id)
);

CREATE TABLE OSUSER
(
  id NUMERIC NOT NULL,
  name VARCHAR(255),
  passwordHash VARCHAR(255),
  CONSTRAINT PK_OSUSER PRIMARY KEY (id)
);

CREATE TABLE OS_PROPERTYENTRY
(
  id NUMERIC NOT NULL,
  entityName VARCHAR(255),
  entityId NUMERIC,
  type int,
  keyValue VARCHAR(255),
  CONSTRAINT PK_OS_PROPERTYENTRY PRIMARY KEY (id)
);


CREATE TABLE OS_PROPERTYDECIMAL
(
  id NUMERIC NOT NULL,
  value NUMERIC,
  CONSTRAINT PK_OS_PROPERTYDECIMAL PRIMARY KEY (id)
);

CREATE TABLE OS_PROPERTYNUMBER
(
  id NUMERIC NOT NULL,
  value NUMERIC,
  CONSTRAINT PK_OS_PROPERTYNUMBER PRIMARY KEY (id)
);

CREATE TABLE OS_PROPERTYSTRING
(
  id NUMERIC NOT NULL,
  value TEXT,
  CONSTRAINT PK_OS_PROPERTYSTRING PRIMARY KEY (id)
);

CREATE TABLE OS_PROPERTYDATA
(
  id NUMERIC NOT NULL,
  value varbinary(2000),
  CONSTRAINT PK_OS_PROPERTYDATA PRIMARY KEY (id)
);

CREATE TABLE OS_PROPERTYDATE
(
  id NUMERIC NOT NULL,
  value TIMESTAMP,
  CONSTRAINT PK_OS_PROPERTYDATE PRIMARY KEY (id)
);